# Generated by Django 4.1.2 on 2022-10-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catName", models.CharField(max_length=20)),
                ("catDesc", models.TextField()),
            ],
        ),
    ]
